import { defineConfig, globalIgnores } from 'eslint/config';
import node from '@kb/eslint-config/node';

export default defineConfig(
  node,
  // Generated by `pnpm db:types`.
  globalIgnores(['src/supabase/database.types.ts']),
  {
    languageOptions: { parserOptions: { tsconfigRootDir: import.meta.dirname } },
  },
);
